# Generated by Django 4.1.5 on 2023-02-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyVet', '0002_alter_paciente_esta_castrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='proximo_control',
            field=models.DateField(blank=True, null=True),
        ),
    ]
